import { Injectable } from "@angular/core";
import { Router } from "@angular/router";
import { Angular2Apollo } from "angular2-apollo";
import { ApolloQueryResult } from "apollo-client";
import gql from "graphql-tag";

import { User, Login, PersistenceService } from "../";

@Injectable()
export class LoginService {
  public email: string;
  public oldPassword: string;
  private tokenKey: string = "loginToken";
  private token: string;

  get isLoggedIn(): boolean {
    return !!this.token;
  }

  constructor(
    private apollo: Angular2Apollo,
    private persistence: PersistenceService,
    private router: Router,
  ) {
    persistence.read<string>(this.tokenKey)
      .then(token => this.token = token);
  }

  /**
   * Perform a user login.
   * @param user The user credentials.
   */
  public login(user: Login): Promise<User> {
    return this.apollo
      .query({
        query: gql`
          query login($email: String!, $password: String!) {
            login(email: $email, password: $password) {
              autoGenerated
            }
          }
        `,
        variables: {
          email: user.email,
          password: user.password,
        },
      })
      .then((result: ApolloQueryResult) => {
        const foundUser = result.data.login as User;

        if (!foundUser) {
          return Promise.reject<User>("User not found");
        }

        this.token = "2131";
        this.persistence.write(this.tokenKey, this.token)
          .catch(err => this.log("login", "Persist token failed", err));

        if (foundUser.autoGenerated) {
          this.oldPassword = user.password;
          this.email = user.email;
        }

        return Promise.resolve(foundUser);
      });
  }

  public logoff() {
    this.clearToken();
  }

  public resetPassword(email) {
    return Promise.resolve();
  }

  /**
   * Change password for user. Uses stored user information.
   * @param newPassword The new password.
   */
  public changePassword(newPassword: string): Promise<void> {
    return this.apollo
      .mutate({
        mutation: gql`
          mutation changePassword($email: String!, $oldPassword: String!, $newPassword: String!) {
            changePassword(email: $email, oldPassword: $oldPassword, newPassword: $newPassword) {
              updatedAt
              autoGenerated
            }
          }
        `,
        variables: {
          email: this.email,
          oldPassword: this.oldPassword,
          newPassword,
        },
      })
      .catch((error) => {
        this.email = undefined;
        this.oldPassword = undefined;
        return Promise.reject("failed update");
      });
  }

  public handleErrors(error) {
    console.log(JSON.stringify(error));
    return Promise.reject(error.message);
  }

  private clearToken(): Promise<string> {
    this.token = "";
    return this.persistence.write(this.tokenKey, "")
      .catch(err => this.log("logoff", "Failed clear token", err));
  }

  private log(method: string, message: string, ...data: Array<any>): void {
    console.log(`LoginService.${method}(): ${message}`, ...data);
  }
}
